LBHackney-IT/tenure-api

- terraform/development/dynamodb.tf
- terraform/production/dynamodb.tf
- terraform/staging/dynamodb.tf
Dynamodb update added to all terraform environments
> dynamodb resource update

- TenureInformationApi/appsettings.LocalDevelopment.json
- TenureInformationApi/appsettings.json
Solving issues in AWS Development - the dynamodb is failing to find the table as it's looking in the wrong AWS Region
> changed region to be eu-west-2

- TenureInformationApi/Startup.cs
[https://hackney.atlassian.net/browse/MTTL-778](https://hackney.atlassian.net/browse/MTTL-778)
Enable CORs for Tenure API
> Enable cors

- TenureInformationApi.Tests/TenureInformationApi.Tests.csproj
- TenureInformationApi.Tests/V1/Boundary/Validation/GetByIdRequestValidatorTests.cs
- TenureInformationApi.Tests/V1/Controllers/TenureInformationControllerTests.cs
- TenureInformationApi.Tests/V1/E2ETests/E2EGetByIdTest.cs
- TenureInformationApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- TenureInformationApi.Tests/V1/UseCase/GetByIdUseCaseTests.cs
- TenureInformationApi/Startup.cs
- TenureInformationApi/TenureInformationApi.csproj
- TenureInformationApi/V1/Boundary/Requests/GetByIdRequest.cs
- TenureInformationApi/V1/Boundary/Requests/Validation/GetByIdRequestValidator.cs
- TenureInformationApi/V1/Controllers/TenureInformationController.cs
- TenureInformationApi/V1/Gateways/DynamoDbGateway.cs
- TenureInformationApi/V1/Gateways/ITenureGateway.cs
- TenureInformationApi/V1/UseCase/GetByIdUseCase.cs
- TenureInformationApi/V1/UseCase/Interfaces/IGetByIdUseCase.cs
https://hackney.atlassian.net/browse/MTTL-723
* Use fluent validation
> Implemented fluent validation

- TenureInformationApi/V1/Domain/Enums.cs
We have updated the following 2 enum objects:
>  enum updated

- TenureInformationApi.Tests/V1/E2ETests/E2EGetByIdTest.cs
- TenureInformationApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
https://hackney.atlassian.net/browse/MTTL-878
Added test coverage for a null `TenuredAsset.Type` value.
> Added tests for a null TenuredAsset.Type value

- TenureInformationApi.Tests/V1/Domain/TenureInformationTests.cs
- TenureInformationApi.Tests/V1/Factories/EntityFactoryTest.cs
- TenureInformationApi/V1/Boundary/Response/TenureResponseObject.cs
- TenureInformationApi/V1/Domain/TenureInformation.cs
- TenureInformationApi/V1/Factories/EntityFactory.cs
- TenureInformationApi/V1/Infrastructure/TenureInformationDb.cs
https://hackney.atlassian.net/browse/MTTL-855
> MTTL-855 - Added functionality + formatted code

- TenureInformationApi.Tests/V1/Domain/TenureHelpersTests.cs
- TenureInformationApi.Tests/V1/Factories/EntityFactoryTest.cs
- TenureInformationApi.Tests/V1/Helper/DatabaseEntityHelper.cs
- TenureInformationApi/V1/Domain/TenureHelpers.cs
- TenureInformationApi/V1/Domain/TenureInformation.cs
- TenureInformationApi/V1/Factories/EntityFactory.cs
- TenureInformationApi/V1/Infrastructure/TenureInformationDb.cs
https://hackney.atlassian.net/browse/MTTL-1120
Corrects the calculation and (non) storage of the tenure IsActive flag
> Correct tenure IsActive use

- TenureInformationApi.Tests/V1/Domain/TenureHelpersTests.cs
- TenureInformationApi.Tests/V1/Factories/EntityFactoryTest.cs
- TenureInformationApi.Tests/V1/Helper/DatabaseEntityHelper.cs
- TenureInformationApi/V1/Domain/TenureHelpers.cs
- TenureInformationApi/V1/Domain/TenureInformation.cs
- TenureInformationApi/V1/Factories/EntityFactory.cs
- TenureInformationApi/V1/Infrastructure/TenureInformationDb.cs
Push tenure IsActive fixes to Staging/Production
> Release mttl 1120

- TenureInformationApi/Startup.cs
- TenureInformationApi/TenureInformationApi.csproj
https://hackney.atlassian.net/browse/MTTL-1119.
> Updated Hackney.Core package version

- CODEOWNERS
- TenureInformationApi/Startup.cs
- TenureInformationApi/TenureInformationApi.csproj
Release logging changes to staging
> Release mttl 1101

- TenureInformationApi/Startup.cs
- TenureInformationApi/TenureInformationApi.csproj
https://hackney.atlassian.net/browse/MTTL-1246
> Use individual Hackney.Core nuget packages

- terraform/development/main.tf
https://hackney.atlassian.net/browse/MTTL-1461
Updated CW dashboard to include widgets for DynamoDB and the SNS topic
New  widgets added to the dashboard
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.
> updated CW dashboard

- terraform/production/dynamodb.tf
- terraform/production/main.tf
- terraform/production/variables.tf
- terraform/staging/dynamodb.tf
- terraform/staging/main.tf
- terraform/staging/variable.tf
https://hackney.atlassian.net/browse/MTTL-1461
Get metric and log data in an easy to view Cloudwatch dashboard
Added Cloudwatch dashboard for staging and prod 
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.
> added TF code for staging and production

- TenureInformationApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- TenureInformationApi/V1/Gateways/DynamoDbGateway.cs
Use camel case in the raised event
> Use camel case in the event

- .circleci/config.yml
We want to deploy to dev from al feature branches to keep Master in a working state
Removed filter to deploy to development
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.
> deploy to dev for all PR's

- TenureInformationApi.Tests/TenureInformationApi.Tests.csproj
- TenureInformationApi.Tests/V1/Controllers/TenureInformationControllerTests.cs
- TenureInformationApi.Tests/V1/E2ETests/Fixtures/TenureFixture.cs
- TenureInformationApi.Tests/V1/E2ETests/Steps/GetTenureStep.cs
- TenureInformationApi.Tests/V1/E2ETests/Steps/PatchTenureStep.cs
- TenureInformationApi.Tests/V1/Factories/ResponseFactoryTest.cs
- TenureInformationApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- TenureInformationApi.Tests/V1/UseCase/GetByIdUseCaseTests.cs
- TenureInformationApi/Startup.cs
- TenureInformationApi/TenureInformationApi.csproj
- TenureInformationApi/V1/Controllers/TenureInformationController.cs
- TenureInformationApi/V1/Domain/TenureInformation.cs
- TenureInformationApi/V1/Factories/EntityFactory.cs
- TenureInformationApi/V1/Infrastructure/HeaderConstants.cs
- TenureInformationApi/V1/Infrastructure/TenureInformationDb.cs
- TenureInformationApi/V1/UseCase/GetByIdUseCase.cs
- TenureInformationApi/V1/UseCase/Interfaces/IGetByIdUseCase.cs
- docker-compose.yml
[Jira Ticket](https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-1509)
Updated the GetByID endpoint to return ETag headers
> Get TenureByID to return ETag headers

- TenureInformationApi.Tests/V1/Controllers/TenureInformationControllerTests.cs
- TenureInformationApi.Tests/V1/UseCase/EditTenureDetailsUseCaseTests.cs
- TenureInformationApi/GlobalSuppressions.cs
- TenureInformationApi/V1/Controllers/TenureInformationController.cs
- TenureInformationApi/V1/Factories/ISnsFactory.cs
- TenureInformationApi/V1/Factories/TenureSnsFactory.cs
- TenureInformationApi/V1/Infrastructure/JWT/CreateTenureEventConstants.cs
- TenureInformationApi/V1/Infrastructure/JWT/PersonAddedToTenureConstants.cs
- TenureInformationApi/V1/Infrastructure/JWT/UpdateTenureConstants.cs
- TenureInformationApi/V1/UseCase/EditTenureDetailsUseCase.cs
- TenureInformationApi/V1/UseCase/Interfaces/IEditTenureDetailsUseCase.cs
- TenureInformationApi/V1/UseCase/PostNewTenureUseCase.cs
- TenureInformationApi/V1/UseCase/UpdateTenureForPersonUseCase.cs
[Jira ticket](https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-1219)
Raise a TenureUpdatedEvent when tenure details updated.
- Event should only be called when changes are made. Request parameters are optional.
Other Changes
- Tenure Factory methods renamed to make purpose more clear.
> Raise TenureUpdatedEvent in TenureAPI

- TenureInformationApi.Tests/V1/Controllers/TenureInformationControllerTests.cs
- TenureInformationApi.Tests/V1/E2ETests/Steps/EditTenureDetailsStep.cs
- TenureInformationApi.Tests/V1/E2ETests/Stories/EditTenureDetailsTests.cs
- TenureInformationApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- TenureInformationApi.Tests/V1/UseCase/EditTenureDetailsUseCaseTests.cs
- TenureInformationApi/V1/Controllers/TenureInformationController.cs
- TenureInformationApi/V1/Gateways/DynamoDbGateway.cs
- TenureInformationApi/V1/Gateways/ITenureGateway.cs
- TenureInformationApi/V1/Infrastructure/Exceptions/VersionNumberConflictException.cs
- TenureInformationApi/V1/UseCase/EditTenureDetailsUseCase.cs
- TenureInformationApi/V1/UseCase/Interfaces/IEditTenureDetailsUseCase.cs
[Jira ticket](https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-1539)
Implement If-Match when editing a tenure.
If the provided IfMatch header doesn't match the tenure VersionNumber, a 409 Conflict response will be returned.
I will not merge this until the frontend has been completed.
> Implement If-Match when editing a tenure

- .circleci/config.yml
- TenureInformationApi.Tests/V1/Controllers/TenureInformationControllerTests.cs
- TenureInformationApi.Tests/V1/E2ETests/Steps/PatchTenureStep.cs
- TenureInformationApi.Tests/V1/E2ETests/Stories/PatchTenureTests.cs
- TenureInformationApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- TenureInformationApi.Tests/V1/UseCase/UpdateTenureForPersonUseCaseTests.cs
- TenureInformationApi/V1/Controllers/TenureInformationController.cs
- TenureInformationApi/V1/Gateways/DynamoDbGateway.cs
- TenureInformationApi/V1/Gateways/ITenureGateway.cs
- TenureInformationApi/V1/UseCase/Interfaces/IUpdateTenureForPersonUseCase.cs
- TenureInformationApi/V1/UseCase/UpdateTenureForPersonUseCase.cs
> Release mttl 1508

- TenureInformationApi/Startup.cs
- TenureInformationApi/serverless.yml
[Jira Ticket](https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?selectedIssue=MTTL-1416)
updating API to ensure that when an x-correlation-id is sent in the request, that it gets logged appropriately
> added x-correlation-id header

- TenureInformationApi.Tests/V1/Controllers/TenureInformationControllerTests.cs
- TenureInformationApi.Tests/V1/E2ETests/Steps/PatchTenureStep.cs
- TenureInformationApi.v3.ncrunchsolution
- TenureInformationApi/V1/Controllers/TenureInformationController.cs
https://hackney.atlassian.net/browse/MTTL-1508
Making the If-Match code consistent between both PATCH endpoints
Made both endpoints use same code
> making If-Match code match

- TenureInformationApi/V1/Boundary/Requests/UpdateTenureRequestObject.cs
- TenureInformationApi/V1/Boundary/Requests/Validation/UpdateTenureRequestValidation.cs
- TenureInformationApi/V1/Factories/UpdateRequestFactory.cs
Add a link to the JIRA ticket that the changes in this PR describe.
Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
Add descriptions of what changes were made to address the problem and provide a solution.
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.
> For release2

- TenureInformationApi/serverless.yml
[Jira Ticket](https://hackney.atlassian.net/browse/MTTL-2305)
Update the endpoint in API Gateway to be regional
This is so we can enable WAF in the future
> Updated endpoint to be regional

- .circleci/config.yml
- TenureInformationApi/serverless.yml
[JIRA ticket](https://hackney.atlassian.net/browse/MTTL-2398)
- update config.yml and serverless.yml to be enabled WAF
> Enable WAF

- .circleci/config.yml
- TenureInformationApi.Tests/MockWebApplicationFactory.cs
- TenureInformationApi.Tests/TenureInformationApi.Tests.csproj
- TenureInformationApi.Tests/V1/E2ETests/Fixtures/TenureFixture.cs
- TenureInformationApi.Tests/V1/E2ETests/Stories/AddPersonToTenureTests.cs
- TenureInformationApi.Tests/V1/E2ETests/Stories/DeletePersonFromTenureTests.cs
- TenureInformationApi.Tests/V1/E2ETests/Stories/EditTenureDetailsTests.cs
- TenureInformationApi.Tests/V1/E2ETests/Stories/PostTenureTests.cs
- docker-compose.yml
https://hackney.atlassian.net/browse/MTTL-2869
Upgrade `Hackney.Core.Testing.Sns` version to fix bug where tests are falsely passing.
> MTTL-2869: Upgrade Hackney.Core.Testing.Sns version 

- .circleci/config.yml
- TenureInformationApi.Tests/Dockerfile
https://hackney.atlassian.net/jira/software/projects/MTTL/boards/47?assignee=624c20c6a629c30068a81020&selectedIssue=MTTL-2956
Resolve SonarCloud Issues
> SonarCloud Issue

- TenureInformationApi.Tests/V1/Gateways/DynamoDbGatewayTests.cs
- TenureInformationApi.Tests/V1/UseCase/EditTenureDetailsUseCaseTests.cs
- TenureInformationApi/V1/Gateways/DynamoDbGateway.cs
- TenureInformationApi/V1/UseCase/EditTenureDetailsUseCase.cs
- Replace `LogDebug` with `LogInformation`
- In DynamoDbGateway, move load and save logging into private methods
- In DynamoDbGateway, add logging when calling each method
- Add logging to EditTenureDetailsUseCase
> Improve logging

- .circleci/config.yml
- TenureInformationApi.Tests/Dockerfile
- terraform/development/dynamodb.tf
- terraform/production/dynamodb.tf
- terraform/staging/dynamodb.tf
- Move the PR #146 changes from `master` branch to `release` branch. 
- We've done smoke-testing on the `development` environment - the GET, PATCH, POST (ones we're tweaking) endpoints are behaving as expected.
- Co-authored: @Miles-Alford 
- Sonar Cloud scan is failing due to missing codecov reporting configuration [Tech Debt].
> Move the PR #146 changes from `master` to `release`.

- TenureInformationApi.Tests/TenureInformationApi.Tests.csproj
- TenureInformationApi/TenureInformationApi.csproj
https://hackney.atlassian.net/browse/TS-1405
Updated version of Hackney.Shared.Tenure to include the AssignedOfficer Id.
> TS-1505: Add reference to new package version

- .circleci/config.yml
Was failing to deploy because it had node but did not have npm
> Fix node install

- .circleci/config.yml
- CODEOWNERS
- Makefile
- TenureInformationApi.Tests/Dockerfile
- TenureInformationApi.Tests/MockWebApplicationFactory.cs
- TenureInformationApi.Tests/TenureInformationApi.Tests.csproj
- TenureInformationApi.Tests/V1/Controllers/BaseControllerTests.cs
- TenureInformationApi/Dockerfile
- TenureInformationApi/TenureInformationApi.csproj
- TenureInformationApi/V1/Controllers/TenureInformationController.cs
- TenureInformationApi/build.cmd
- TenureInformationApi/build.sh
- TenureInformationApi/serverless.yml
[HPT-610](https://hackney.atlassian.net/browse/HPT-610) Dotnet 8 Upgrade
[HPT-610]: https://hackney.atlassian.net/browse/HPT-610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release Dotnet 8 Upgrade

- terraform/development/dynamodb.tf
- terraform/development/variables.tf
- terraform/production/dynamodb.tf
- terraform/production/variables.tf
- terraform/staging/dynamodb.tf
- terraform/staging/variable.tf
> Release: Set dynamodb stream from vars

- .circleci/config.yml
- TenureInformationApi/V1/Controllers/TenureInformationController.cs
- TenureInformationApi/serverless.yml
[HPT-641](https://hackney.atlassian.net/browse/HPT-641) Restricted Access 
Disallow access for a specific record for a specific user
[HPT-641]: https://hackney.atlassian.net/browse/HPT-641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Restrict endpoint exception

- TenureInformationApi/V1/Controllers/TenureInformationController.cs
- TenureInformationApi/serverless.yml
- terraform/production/variables.tf
> Release endpoint restriction exception

- .circleci/config.yml
> Release fix prod deploy - separate terraform and api

- TenureInformationApi/serverless.yml
Update staging lambda authorizer
- Hardcode authorizer ARNs in serverless, preventing any unintended changes via parameter store
- Update staging authorizer to the new version
> Update dev and staging lambda authorizer

- TenureInformationApi/serverless.yml
Updated production authorizer ARN
> Update production authorizer ARN
